name: pt_popdic
description: A new Flutter project.

version: 1.0.0+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  provider: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  